export const obj = [
  {
    "id": 1,
    "road": "Ahilyanagar to Pune",
    "layout": "2 x 2",
    "type": "AC",
    "StartTime": "08:00 AM",
    "EndTime": "04:30 PM",
    "pickup": "Ahilyanagar",
    "distance": "127 km",
    "drop": "Pune",
    "price": "230.00",
    "offdays": ["Friday", "Monday"],
    "Facilities": ["Water Bottle", "WiFi"]
  },
  {
    "id": 2,
    "road": "Pune to Mumbai",
    "layout": "2 x 1",
    "type": "NO-AC",
    "StartTime": "10:00 AM",
    "EndTime": "02:00 PM",
    "pickup": "Pune",
    "distance": "150 km",
    "drop": "Mumbai",
    "price": "300.00",
    "offdays": ["Sunday"],
    "Facilities": ["Newspapers", "Charging Points"]
  },
  {
    "id": 3,
    "road": "Sambaji Nagar to Pune",
    "layout": "2 x 2",
    "type": "CLASSIC",
    "StartTime": "06:00 AM",
    "EndTime": "11:30 AM",
    "pickup": "Sambaji Nagar",
    "distance": "210 km",
    "drop": "Pune",
    "price": "350.00",
    "offdays": ["Thursday", "Saturday"],
    "Facilities": ["Water Bottle", "Snacks"]
  },
  {
    "id": 4,
    "road": "Ahilyanagar to Pune",
    "layout": "2 x 2",
    "type": "NO-AC",
    "StartTime": "01:00 PM",
    "EndTime": "09:00 PM",
    "pickup": "Ahilyanagar",
    "distance": "127 km",
    "drop": "Pune",
    "price": "200.00",
    "offdays": ["Tuesday", "Thursday"],
    "Facilities": ["WiFi", "Charging Points"]
  },
  {
    "id": 5,
    "road": "Pune to Mumbai",
    "layout": "2 x 2",
    "type": "CLASSIC",
    "StartTime": "09:00 PM",
    "EndTime": "01:30 AM",
    "pickup": "Pune",
    "distance": "150 km",
    "drop": "Mumbai",
    "price": "320.00",
    "offdays": ["Saturday", "Sunday"],
    "Facilities": ["WiFi", "Blankets"]
  },
  {
    "id": 6,
    "road": "Pune to Sambaji Nagar",
    "layout": "2 x 1",
    "type": "NO-AC",
    "StartTime": "05:00 PM",
    "EndTime": "10:30 PM",
    "pickup": "Pune",
    "distance": "210 km",
    "drop": "Sambaji Nagar",
    "price": "280.00",
    "offdays": ["Monday", "Wednesday"],
    "Facilities": ["Water Bottle", "Newspapers"]
  }
];
export const SeatData = [
  { id: 1, seat: "A1", selected:"true" },
  { id: 2, seat: "A2", selected:"true" },
  { id: 3, seat: "A3", selected:"true" },
  { id: 4, seat: "A4", selected:"true" },
  { id: 5, seat: "B1", selected:"true" },
  { id: 6, seat: "B2", selected:"true"  },
  { id: 7, seat: "B3", selected:"true"  },
  { id: 8, seat: "B4", selected:"true"  },
  { id: 9, seat: "C1", selected:"true"  },
  { id: 10, seat: "C2", selected:"true"  },
  { id: 11, seat: "C3", selected:"true"  },
  { id: 12, seat: "C4", selected:"true"  },
  { id: 13, seat: "D1", selected:"true"  },
  { id: 14, seat: "D2", selected:"true"  },
  { id: 15, seat: "D3", selected:"true"  },
  { id: 16, seat: "D4", selected:"true"  },
  { id: 17, seat: "E1", selected:"true"  },
  { id: 18, seat: "E2", selected:"true"  },
  { id: 19, seat: "E3", selected:"true"  },
  { id: 20, seat: "E4", selected:"true"  },
  { id: 21, seat: "F1", selected:"true"  },
  { id: 22, seat: "F2", selected:"true"  },
  { id: 23, seat: "F3", selected:"true"  },
  { id: 24, seat: "F4", selected:"true"  },
  { id: 25, seat: "G1", selected:"true"  },
  { id: 26, seat: "G2", selected:"true"  },
  { id: 27, seat: "G3", selected:"true"  },
  { id: 28, seat: "G4", selected:"true"  },
  { id: 29, seat: "H1", selected:"true"  },
  { id: 30, seat: "H2", selected:"true"  },
  { id: 31, seat: "H3", selected:"true"  },
  { id: 32, seat: "H4", selected:"true"  },
  { id: 33, seat: "I1", selected:"true"  },
  { id: 34, seat: "I2", selected:"true"  },
  { id: 35, seat: "I3", selected:"true"  },
  { id: 36, seat: "I4", selected:"true"  },
  { id: 37, seat: "J1", selected:"true"  },
  { id: 38, seat: "J2", selected:"true"  },
  { id: 39, seat: "J3", selected:"true"  },
  { id: 40, seat: "J4", selected:"true"  },
  { id: 41, seat: "K1", selected:"true"  },
  { id: 42, seat: "K2", selected:"true"  },
  { id: 43, seat: "K3", selected:"true"  },
  { id: 44, seat: "K4", selected:"true"  },
 
];




